### ISSUE TITLE
update to develop panel error

### ISSUE THREAD

**Issue by HassanMohammadi** [hiddify/Hiddify-Manager#3392]
Could not build url for endpoint 'admin.static' with values ['filename', 'proxy_path', 'user_secret', 'v']. Did you mean 'adminlte.static' instead?
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.10/dist-packages/flask_admin/base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/flask_admin/base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/flask_admin/model/base.py", line 2017, in index_view
    return self.render(
  File "/usr/local/lib/python3.10/dist-packages/flask_admin/base.py", line 308, in render
    return render_template(template, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/flask/templating.py", line 154, in render_template
    return _render(
  File "/usr/local/lib/python3.10/dist-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/templates/model/user_list.html", line 1, in top-level template code
    {% extends 'hiddify-flask-admin/list.html' %}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/templates/hiddify-flask-admin/list.html", line 6, in top-level template code
    {% import 'flask-admin/model/row_actions.html' as row_actions with context %}
  File "/usr/local/lib/python3.10/dist-packages/flask_adminlte3/templates/flask-admin/master.html", line 1, in top-level template code
    {% extends admin_base_template %}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/templates/flaskadmin-layout.html", line 1, in top-level template code
    {% extends 'admin-layout.html' %}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/templates/admin-layout.html", line 2, in top-level template code
    {% from 'macros.html' import icon,render_nav_item %}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/templates/master.html", line 327, in top-level template code
    {% block tail %}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/templates/hiddify-flask-admin/list.html", line 203, in block 'tail'
    <script src="{{ admin_static.url(filename='admin/js/bs4_modal.js', v='1.0.0') }}"></script>
  File "/usr/local/lib/python3.10/dist-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
  File "/usr/local/lib/python3.10/dist-packages/flask_admin/templates/bootstrap4/admin/static.html", line 2, in template
    {{ get_url('{admin_endpoint}.static'.format(admin_endpoint=admin_view.admin.endpoint), *varargs, **kwargs) }}
  File "/usr/local/lib/python3.10/dist-packages/flask_admin/base.py", line 390, in get_url
    return url_for(endpoint, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/flask/helpers.py", line 336, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/usr/local/lib/python3.10/dist-packages/flask/helpers.py", line 323, in url_for
    rv = url_adapter.build(
  File "/usr/local/lib/python3.10/dist-packages/werkzeug/routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'admin.static' with values ['filename', 'proxy_path', 'user_secret', 'v']. Did you mean 'adminlte.static' instead?

**Comment by lymanjre** [comment]
Pls update to the latest version. The issue should be solved. If it exists pls open this issue.
