### ISSUE TITLE
خطای 500 یا 502 سرور و ارور پایتون

### ISSUE THREAD

**Issue by OomoOj** [hiddify/Hiddify-Manager#3403]
سلام.... دیروز تا الان هر کاری میکنم نمتونم وارد پنل بشم همش ارور زیر رو میده

cannot import name 'bot' from 'hiddifypanel.panel.commercial.restapi' (/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/commercial/restapi/__init__.py)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1852, in preprocess_request
    url_func(request.endpoint, request.view_args)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/common.py", line 140, in pull_secret_code
    import hiddifypanel.panel.commercial.telegrambot as telegrambot
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/commercial/telegrambot/__init__.py", line 1, in <module>
    from hiddifypanel.panel.commercial.restapi import bot, register_bot
ImportError: cannot import name 'bot' from 'hiddifypanel.panel.commercial.restapi' (/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/commercial/restapi/__init__.py)

لطفا یکی پراهنماتیی کنه

**Comment by lymanjre** [comment]
لطفا به آخرین نسخه آپدیت کنید. مشکل باید رفع شده باشه. در صورت وجود مشکل ایشو را باز نمایید.
