### ISSUE TITLE
Internal server error: replace

### ISSUE THREAD

**Issue by amehri** [hiddify/Hiddify-Manager#3445]
# Internal Error Stacktrace:
**Error Message**:   'IPv4Address' object has no attribute 'replace'
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/Actions.py", line 186, in update
    return self.update2()
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/hiddify.py", line 75, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/Actions.py", line 205, in update2
    domains=get_domains(),
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/Actions.py", line 260, in get_domains
    return [d.domain.replace("*", hiddify.get_random_string(3, 6)) for d in get_panel_domains(always_add_all_domains=True, always_add_ip=True)]
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/Actions.py", line 260, in <listcomp>
    return [d.domain.replace("*", hiddify.get_random_string(3, 6)) for d in get_panel_domains(always_add_all_domains=True, always_add_ip=True)]

```

## Details:
**Hiddify Version**: 9.0.0.dev26
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-76-generic-x86_64-with-glibc2.35
**User Agent**:      Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36

**Comment by lymanjre** [comment]
Pls update to the latest version. The issue should be solved. If it exists pls open this issue.
