### ISSUE TITLE
Internal server error: Unknown

### ISSUE THREAD

**Issue by nillxinix** [hiddify/Hiddify-Manager#3455]
# Internal Error Stacktrace:
**Error Message**:   Object of type IPv4Address is not JSON serializable
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/user/user.py", line 350, in all_configs
    resp = link_maker.make_v2ray_configs(**c)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/user/link_maker.py", line 799, in make_v2ray_configs
    link = to_link(pinfo)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/user/link_maker.py", line 266, in to_link
    return "vmess://" + hiddify.do_base_64(f'{json.dumps(vmess_data)}')

```

## Details:
**Hiddify Version**: 9.0.0.dev26
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-88-generic-x86_64-with-glibc2.35
**User Agent**:      Mozilla/5.0 (Android 13; Mobile; rv:122.0) Gecko/122.0 Firefox/122.0

**Comment by lymanjre** [comment]
Pls update to the latest version. The issue should be solved. If it exists pls open this issue.
