### ISSUE TITLE
Internal server error: Unknown

### ISSUE THREAD

**Issue by amaleky** [hiddify/Hiddify-Manager#3475]
# Internal Error Stacktrace:
**Error Message**:   Object of type IPv4Address is not JSON serializable
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/user/user.py", line 321, in full_singbox
    resp = link_maker.make_full_singbox_config(**c)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/user/link_maker.py", line 750, in make_full_singbox_config
    res = json.dumps(base_config, indent=4)

```

## Details:
**Hiddify Version**: X.X.X.devX
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-89-generic-x86_64-with-glibc2.35
**User Agent**:      Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

**Comment by lymanjre** [comment]
Pls update to the latest version. The issue should be solved. If it exists pls open this issue.
