### ISSUE TITLE
Internal server error: account

### ISSUE THREAD

**Issue by it-saeed** [hiddify/Hiddify-Manager#3526]
# Internal Error Stacktrace:
**Error Message**:   account
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/common_bp/login.py", line 58, in post
    return render_template('login.html', form=LoginForm())
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/common_bp/templates/login.html", line 2, in top-level template code
    {% extends "master.html" %}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/templates/master.html", line 9, in top-level template code
    {% block head_meta %}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/templates/master.html", line 23, in block 'head_meta'
    <link href="{{static_url_for(filename='images/splash/iphone5_splash.png')}}" media="(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" rel="apple-touch-startup-image" />
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/hutils/utils.py", line 42, in static_url_for
    orig = url_for("static", **values)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/common.py", line 110, in add_proxy_path_user
    elif g.account and hiddify.is_admin_role(g.account.role):

```

## Details:
**Hiddify Version**: 9.0.0.dev50
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-91-generic-aarch64-with-glibc2.35
**User Agent**:      Unknown

**Comment by lymanjre** [comment]
Pls update to the latest version. The issue should be solved. If it exists pls open this issue.
