### ISSUE TITLE
Internal server error: ApplyMode

### ISSUE THREAD

**Issue by amaleky** [hiddify/Hiddify-Manager#3615]
# Internal Error Stacktrace:
**Error Message**:   name 'ApplyMode' is not defined
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/auth.py", line 111, in decorated_view
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/ProxyAdmin.py", line 58, in post
    hutils.flask.flash_config_success(restart_mode=ApplyMode.apply, domain_changed=False)

```

## Details:
**Hiddify Version**: 02-07T20:59
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-94-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by Iam54r1n4** [comment]
Fixed.
