### ISSUE TITLE
Internal server error: Unknown

### ISSUE THREAD

**Issue by abbasboveiry** [hiddify/Hiddify-Manager#3636]
# Internal Error Stacktrace:
**Error Message**:   list index out of range
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/user/user.py", line 32, in index
    return self.auto_sub()
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/user/user.py", line 36, in auto_sub
    return self.new()
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/auth.py", line 111, in decorated_view
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/user/user.py", line 92, in new
    c = get_common_data(g.account.uuid, mode="new")
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/user/user.py", line 299, in get_common_data
    db_domain = domains_valid[0]

```

## Details:
**Hiddify Version**: 02-17T18:14
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-60-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by Iam54r1n4** [comment]
Thanks for your report. Fixed.
