### ISSUE TITLE
Internal server error: Unknown 

### ISSUE THREAD

**Issue by MajidRB** [hiddify/Hiddify-Manager#3649]
# Internal Error Stacktrace:
**Error Message**:   'type'
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/auth.py", line 111, in decorated_view
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/commercial/restapi/v2/user/configs_api.py", line 119, in get
    f"{link_maker.to_link(pinfo)}"
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/user/link_maker.py", line 399, in to_link
    if  proxy['l3'] == ProxyL3.http and proxy['type'] == 'tcp' and proxy['proto'] in ['vless', 'trojan']:

```

```
500
Oops! something went wrong. Hiddify Panel 9.0.0.dev74
Please create an issue on Github

        
'type'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/auth.py", line 111, in decorated_view
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/flask/views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/flask/views.py", line 158, in dispatch_request
    return current_app.ensure_sync(meth)(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/apiflask/scaffold.py", line 498, in _response
    rv = f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/apiflask/scaffold.py", line 87, in wrapper
    return current_app.ensure_sync(f)(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/commercial/restapi/v2/user/configs_api.py", line 119, in get
    f"{link_maker.to_link(pinfo)}"
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/user/link_maker.py", line 399, in to_link
    if  proxy['l3'] == ProxyL3.http and proxy['type'] == 'tcp' and proxy['proto'] in ['vless', 'trojan']:
KeyError: 'type'
```

## Details:
**Hiddify Version**: 9.0.0.dev74
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-91-generic-aarch64-with-glibc2.35
**User Agent**:      Unknown

**Comment by Iam54r1n4** [comment]
Thanks for your report. Fixed.
