### ISSUE TITLE
after fresh install 8.8.96 i found error 500 for create new user

### ISSUE THREAD

**Issue by mashtiali2023** [hiddify/Hiddify-Manager#3659]
after fresh install 8.8.96 when i want to create new user i found this error

cffi library '_openssl' has no function, constant or global variable named 'Cryptography_HAS_MEM_FUNCTIONS'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.10/dist-packages/flask_admin/base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/flask_admin/base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/flask_admin/model/base.py", line 2088, in create_view
    model = self.create_model(form)
  File "/usr/local/lib/python3.10/dist-packages/flask_admin/contrib/sqla/view.py", line 1165, in create_model
    if not self.handle_view_exception(ex):
  File "/usr/local/lib/python3.10/dist-packages/flask_admin/contrib/sqla/view.py", line 1133, in handle_view_exception
    return super(ModelView, self).handle_view_exception(exc)
  File "/usr/local/lib/python3.10/dist-packages/flask_admin/contrib/sqla/view.py", line 1162, in create_model
    self._on_model_change(form, model, True)
  File "/usr/local/lib/python3.10/dist-packages/flask_admin/model/base.py", line 1569, in _on_model_change
    self.on_model_change(form, model, is_created)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/UserAdmin.py", line 257, in on_model_change
    priv, publ = hiddify.get_ed25519_private_public_pair()
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/hiddify.py", line 783, in get_ed25519_private_public_pair
    privkey = ed25519.Ed25519PrivateKey.generate()
  File "/usr/local/lib/python3.10/dist-packages/cryptography/hazmat/primitives/asymmetric/ed25519.py", line 64, in generate
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/usr/local/lib/python3.10/dist-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/usr/local/lib/python3.10/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 27, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "/usr/local/lib/python3.10/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 167, in <module>
    Binding.init_static_locks()
  File "/usr/local/lib/python3.10/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 134, in init_static_locks
    cls._ensure_ffi_initialized()
  File "/usr/local/lib/python3.10/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 106, in _ensure_ffi_initialized
    cls.lib = build_conditional_library(
  File "/usr/local/lib/python3.10/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 60, in build_conditional_library
    if not getattr(lib, condition):
AttributeError: cffi library '_openssl' has no function, constant or global variable named 'Cryptography_HAS_MEM_FUNCTIONS'

**Comment by mashtiali2023** [comment]
thanks alot

my version upgraded to 8.8.97 and problem solved

Regards
