### ISSUE TITLE
Internal server error: type

### ISSUE THREAD

**Issue by waseemcn** [hiddify/Hiddify-Manager#3663]
# Internal Error Stacktrace:
**Error Message**:   'bool' object has no attribute 'type'
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/auth.py", line 111, in decorated_view
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/Actions.py", line 196, in update_usage
    out_msg=f'<pre class="ltr">{json.dumps(usage.update_local_usage(),indent=2)}</pre>',
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/usage.py", line 15, in update_local_usage
    return add_users_usage(res, child_id=0)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/usage.py", line 87, in add_users_usage
    if have_change and hconfig(ConfigEnum.core_type == 'singbox'):
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/models/config.py", line 51, in hconfig
    if key.type == bool:

```

## Details:
**Hiddify Version**: 9.0.0.dev75
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-83-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by waseemcn** [comment]
500
Oops! something went wrong. Hiddify Panel 9.0.0.dev75
Please create an issue on Github

        
405 Method Not Allowed: The method is not allowed for the requested URL.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1499, in dispatch_request
    self.raise_routing_exception(req)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1481, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/flask/ctx.py", line 397, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/werkzeug/routing.py", line 2044, in match
    raise MethodNotAllowed(valid_methods=list(have_match_for))
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.

**Comment by waseemcn** [comment]
nginx-access.log
Failure to log

**Comment by Iam54r1n4** [comment]
Thanks. Fixed.
