### ISSUE TITLE
Error 500 when trying to see the logs

### ISSUE THREAD

**Issue by omidshojaee** [hiddify/Hiddify-Manager#3698]
**Describe the bug**

Hiddify Manager v8.8.97.

**To Reproduce**
1. Make any kind of changes.
2. While you're waiting for 5 minutes for changes to apply, click on the link to see the full log. This is what you get:

```
500
خطایی رخ داده است!! Hiddify Panel 8.8.97
لطفا با هیدیفای از طریق آدرس ایمیل info@hiddify.com و ذکر مشخصات این صفحه در ارتباط باشید.

        
[Errno 2] No such file or directory: '/opt/hiddify-config//log/system/install.log'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.10/dist-packages/flask_classful.py", line 268, in proxy
    response = view(**request.view_args)
  File "/usr/local/lib/python3.10/dist-packages/flask_classful.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/hiddify.py", line 88, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/Actions.py", line 33, in reverselog
    with open(f'{config_dir}/log/system/{logfile}') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/hiddify-config//log/system/install.log'
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Iam54r1n4** [comment]
Update the panel
