### ISSUE TITLE
error in show panel in  10.10.11 V

### ISSUE THREAD

**Issue by miladj3** [hiddify/Hiddify-Manager#3728]
**Describe the bug**
doesn't show the panel

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: child.name

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/__main__.py", line 13, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/flask/cli.py", line 579, in main
    return super().main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1651, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1698, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/usr/local/lib/python3.10/dist-packages/flask/cli.py", line 535, in get_command
    return info.load_app().cli.get_command(ctx, name)
  File "/usr/local/lib/python3.10/dist-packages/flask/cli.py", line 382, in load_app
    app = self.create_app()
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/base.py", line 129, in create_app_wsgi
    app = create_app()
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/base.py", line 74, in create_app
    init_db()
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/init_db.py", line 621, in init_db
    db_version = int(hconfig(ConfigEnum.db_version) or 0)
  File "/usr/local/lib/python3.10/dist-packages/redis_cache/__init__.py", line 211, in inner
    parsed_result = fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/models/config.py", line 47, in hconfig
    child_id = Child.current.id
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/models/child.py", line 66, in current
    child = Child.by_id(0)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/models/child.py", line 59, in by_id
    return Child.query.filter(Child.id == id).first()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/query.py", line 2824, in first
    return self.limit(1)._iter().first()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/session.py", line 1714, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: child.name
[SQL: SELECT child.id AS child_id, child.name AS child_name, child.mode AS child_mode, child.unique_id AS child_unique_id 
FROM child 
WHERE child.id = ?
 LIMIT ? OFFSET ?]
[parameters: (0, 1, 0)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

**Comment by Iam54r1n4** [comment]
Thanks for your report. update your panel and test it again.
