### ISSUE TITLE
Internal server error: get

### ISSUE THREAD

**Issue by Salim-dovob** [hiddify/Hiddify-Manager#3744]
# Internal Error Stacktrace:
**Error Message**:   'list' object has no attribute 'get'
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/auth.py", line 111, in decorated_view
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/Backup.py", line 47, in post
    hiddify.set_db_from_json(json_data,
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/hiddify.py", line 243, in set_db_from_json
    backup_child_unique_id = get_backup_child_unique_id(json_data)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/hiddify.py", line 481, in get_backup_child_unique_id
    if len(backupdata.get('childs', [])) == 0:

```

## Details:
**Hiddify Version**: 10.10.17
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-87-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by Iam54r1n4** [comment]
Hi,
Your back file is corrupted.
