### ISSUE TITLE
Internal server error: Unknown

### ISSUE THREAD

**Issue by mehdibestboy** [hiddify/Hiddify-Manager#3750]
# Internal Error Stacktrace:
**Error Message**:   
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/auth.py", line 111, in decorated_view
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/Actions.py", line 196, in update_usage
    out_msg=f'<pre class="ltr">{json.dumps(usage.update_local_usage(),indent=2)}</pre>',
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/usage.py", line 14, in update_local_usage
    res = user_driver.get_users_usage(reset=True)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/drivers/user_driver.py", line 15, in get_users_usage
    all_usage = driver.get_all_usage(users)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/drivers/ssh_liberty_bridge_api.py", line 35, in get_all_usage
    return {u: self.get_usage_imp(u.uuid) for u in users}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/drivers/ssh_liberty_bridge_api.py", line 35, in <dictcomp>
    return {u: self.get_usage_imp(u.uuid) for u in users}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/drivers/ssh_liberty_bridge_api.py", line 48, in get_usage_imp
    redis_client.save()

```

## Details:
**Hiddify Version**: 10.10.17
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-43-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by Iam54r1n4** [comment]
Thanks for your report.
First of all update your panel, if doesn't work try running this command:
```bash
cd /opt/; ln -s /opt/hiddify-manager/ hiddify-config
```

**Comment by Hamedb91** [comment]
ln: failed to create symbolic link 'hiddify-config/hiddify-manager': File exists

این کد اجرا نمیشه میشه بگید چیکار باید بکنم

**Comment by Hamedb91** [comment]
> > ln: failed to create symbolic link 'hiddify-config/hiddify-manager': File exists
> > این کد اجرا نمیشه میشه بگید چیکار باید بکنم
> 
> شما نباید چنین مشکلی داشته باشید. پنل رو اپدیت کنید.


آپدیت هم کردم بازم نشد

**Comment by Iam54r1n4** [comment]
لطفا از اخرین ورژن استفاده کنید. روی اخرین ورژن باقی افراد چنین مشکلی ندارند.
