### ISSUE TITLE
Internal server error: Unknown

### ISSUE THREAD

**Issue by mehdisamurai** [hiddify/Hiddify-Manager#3759]
# Internal Error Stacktrace:
**Error Message**:   Command '['sudo', '/opt/hiddify-manager/common/commander.py', 'update-wg-usage']' returned non-zero exit status 1.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/auth.py", line 111, in decorated_view
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/Actions.py", line 196, in update_usage
    out_msg=f'<pre class="ltr">{json.dumps(usage.update_local_usage(),indent=2)}</pre>',
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/usage.py", line 14, in update_local_usage
    res = user_driver.get_users_usage(reset=True)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/drivers/user_driver.py", line 15, in get_users_usage
    all_usage = driver.get_all_usage(users)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/drivers/wireguard_api.py", line 93, in get_all_usage
    all_usages = self.__sync_local_usages()
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/drivers/wireguard_api.py", line 43, in __sync_local_usages
    wg_usage = self.__get_wg_usages()
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/drivers/wireguard_api.py", line 21, in __get_wg_usages
    raw_output = commander(Command.update_wg_usage, run_in_background=False)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/run_commander.py", line 85, in commander
    return subprocess.check_output(base_cmd, cwd=str(current_app.config['HIDDIFY_CONFIG_PATH'])).decode()

```

## Details:
**Hiddify Version**: 10.10.17
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-97-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by Iam54r1n4** [comment]
Fixed.
