### ISSUE TITLE
Internal server error: Cryptography_HAS_MEM_FUNCTIONS

### ISSUE THREAD

**Issue by fovadnabizadeh** [hiddify/Hiddify-Manager#3760]
# Internal Error Stacktrace:
**Error Message**:   cffi library '_openssl' has no function, constant or global variable named 'Cryptography_HAS_MEM_FUNCTIONS'
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/UserAdmin.py", line 275, in on_model_change
    priv, publ = hiddify.get_ed25519_private_public_pair()
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/hiddify.py", line 384, in get_ed25519_private_public_pair
    privkey = ed25519.Ed25519PrivateKey.generate()

```

## Details:
**Hiddify Version**: 10.10.17
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-91-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by Iam54r1n4** [comment]
مشکل در حال بررسی هست. فعلا این issue بسته میشه.
