### ISSUE TITLE
Internal server error: Unknown sub link cdn proxy on

### ISSUE THREAD

**Issue by amin0200** [hiddify/Hiddify-Manager#3763]
# Internal Error Stacktrace:
**Error Message**:   '37.156.155.41, 185.231.114.219' does not appear to be an IPv4 or IPv6 address
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/user/user.py", line 32, in index
    return self.auto_sub()
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/user/user.py", line 36, in auto_sub
    return self.new()
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/auth.py", line 111, in decorated_view
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/user/user.py", line 92, in new
    c = get_common_data(g.account.uuid, mode="new")
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/user/user.py", line 349, in get_common_data
    "ip_debug": hutils.network.auto_ip_selector.get_real_user_ip_debug(user_ip),
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/hutils/network/auto_ip_selector.py", line 114, in get_real_user_ip_debug
    return __get_real_user_ip_debug_imp(user_ip or get_real_user_ip())
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/hutils/network/auto_ip_selector.py", line 119, in __get_real_user_ip_debug_imp
    asnres = IPASN.get(user_ip) or {}

```

## Details:
**Hiddify Version**: 10.10.17
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-91-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by Iam54r1n4** [comment]
Fixed. wait for next release.
