### ISSUE TITLE
Internal server error: Unknown | Users Usage Does Not Get Updated

### ISSUE THREAD

**Issue by amir-reza-bijandi** [hiddify/Hiddify-Manager#3786]
# Internal Error Stacktrace:
**Error Message**:   [Errno 13] Permission denied: './hiddify_usages.json'
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/auth.py", line 111, in decorated_view
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/Actions.py", line 196, in update_usage
    out_msg=f'<pre class="ltr">{json.dumps(usage.update_local_usage(),indent=2)}</pre>',
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/usage.py", line 14, in update_local_usage
    res = user_driver.get_users_usage(reset=True)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/drivers/user_driver.py", line 15, in get_users_usage
    all_usage = driver.get_all_usage(users)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/drivers/wireguard_api.py", line 93, in get_all_usage
    all_usages = self.__sync_local_usages()
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/drivers/wireguard_api.py", line 57, in __sync_local_usages
    with open(WireguardApi.WG_LOCAL_USAGE_FILE_PATH, 'w') as f:

```

## Details:
**Hiddify Version**: 10.10.17
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-91-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

Fresh install of Hiddify and the user usage does not get updated and force updating it causes this error!

**Comment by amir-reza-bijandi** [comment]
I solved the issue using the following command:
`chmod 777 /opt/hiddify-manager/hiddify_usages.json`

**Comment by amir-reza-bijandi** [comment]
I solved the issue using the following command:
`chmod 777 /opt/hiddify-manager/hiddify_usages.json`
