### ISSUE TITLE
Bug with Cloudflare API token and wildcard domain names in the panel 

### ISSUE THREAD

**Issue by A5DkjGQUZx** [hiddify/Hiddify-Manager#3791]
to the get_cert command: {domain}"
AssertionError: Error: Invalid domain passed to the get_cert command: *.MyDomainName.Domain
to the get_cert command: *.MyDomainName.Domain
Traceback (most recent call last):
  File "/opt/hiddify-manager/common/commander.py", line 163, in <module>
    cli()
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/hiddify-manager/common/commander.py", line 139, in get_cert
    assert is_domain_valid(domain), f"Error: Invalid domain passed to the get_cert command: {domain}"
AssertionError: Error: Invalid domain passed to the get_cert command: *.MyDomainName.Domain
/opt/hiddify-manager/common/commander.py", line 163, in <module>
    cli()
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/hiddify-manager/common/commander.py", line 139, in get_cert
    assert is_domain_valid(domain), f"Error: Invalid domain passed to the get_cert command: {domain}"
AssertionError: Error: Invalid domain passed to the get_cert command: *.MyDomainName.Domain

**Comment by moli1369** [comment]
با پاک کردن api وروکر کلودفلر در پنل هیدی فای مشکل حل شد.  پنل نمیتونه ارتباط برقرار کنه با ورکر

**Comment by ReturnFI** [comment]
سلام.
به آخرین نسخه ریلیز آپدیت کنید مشکل برطرف شده

**Comment by litoosh13** [comment]
به آخرین نسخه آپدیت نمایید
آموزش نصب و کانفیگ صحیح پنل:
hiddify.com/manager
hiddify.com/fa/manager
