### ISSUE TITLE
Internal server error: Unknown

### ISSUE THREAD

**Issue by fl0wstream** [hiddify/Hiddify-Manager#3792]
# Internal Error Stacktrace:
**Error Message**:   <ConfigEnum.http_proxy_enable: 'http_proxy_enable'>
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/auth.py", line 111, in decorated_view
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/user/user.py", line 225, in all_configs
    resp = link_maker.make_v2ray_configs(**c)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/user/link_maker.py", line 1012, in make_v2ray_configs
    for pinfo in get_all_validated_proxies(domains):
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/user/link_maker.py", line 1068, in get_all_validated_proxies
    for t in (['http', 'tls'] if hconfigs[ConfigEnum.http_proxy_enable] else ['tls']):

```

## Details:
**Hiddify Version**: 10.10.19
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-100-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by Iam54r1n4** [comment]
Fixed.
