### ISSUE TITLE
Internal server error: reality

### ISSUE THREAD

**Issue by Afx110** [hiddify/Hiddify-Manager#3856]
local variable 'server_asn' referenced before assignment
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.10/dist-packages/flask_admin/base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/flask_admin/base.py", line 369, in _run_view
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/flask_admin/model/base.py", line 2100, in create_view
    model = self.create_model(form)
  File "/usr/local/lib/python3.10/dist-packages/flask_admin/contrib/sqla/view.py", line 1165, in create_model
    if not self.handle_view_exception(ex):
  File "/usr/local/lib/python3.10/dist-packages/flask_admin/contrib/sqla/view.py", line 1133, in handle_view_exception
    return super(ModelView, self).handle_view_exception(exc)
  File "/usr/local/lib/python3.10/dist-packages/flask_admin/contrib/sqla/view.py", line 1162, in create_model
    self._on_model_change(form, model, True)
  File "/usr/local/lib/python3.10/dist-packages/flask_admin/model/base.py", line 1570, in _on_model_change
    self.on_model_change(form, model, is_created)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/DomainAdmin.py", line 237, in on_model_change
    msg = _("selected domain for REALITY is not in the same ASN. To better use of the protocol, it is better to find a domain in the same ASN.")+(f"<br> Server ASN={server_asn}<br>{d}_ASN={domain_asn}" if server_asn or domain_asn else "")
UnboundLocalError: local variable 'server_asn' referenced before assignment

## Details:
**Hiddify Version**: 10.11.1
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-101-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by hiddify-com** [comment]
fixed
