### ISSUE TITLE
با این آپدیت حجم مصرفی و آنلاینی از کارافتادن

### ISSUE THREAD

**Issue by mostafacpr** [hiddify/Hiddify-Manager#3862]
# Bug/Feature:
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 10.12.0
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-91-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by saeed-jalilian** [comment]
i have the same problem and here is the thrown error, hope it helps

# Internal Error Stacktrace:
**Error Message**:   Command '['sudo', '/opt/hiddify-manager/common/commander.py', 'update-wg-usage']' returned non-zero exit status 1.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/auth.py", line 111, in decorated_view
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/Actions.py", line 192, in update_usage
    out_msg=f'<pre class="ltr">{json.dumps(usage.update_local_usage(),indent=2)}</pre>',
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/usage.py", line 14, in update_local_usage
    res = user_driver.get_users_usage(reset=True)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/drivers/user_driver.py", line 15, in get_users_usage
    all_usage = driver.get_all_usage(users)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/drivers/wireguard_api.py", line 93, in get_all_usage
    all_usages = self.__sync_local_usages()
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/drivers/wireguard_api.py", line 43, in __sync_local_usages
    wg_usage = self.__get_wg_usages()
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/drivers/wireguard_api.py", line 21, in __get_wg_usages
    raw_output = commander(Command.update_wg_usage, run_in_background=False)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/run_commander.py", line 85, in commander
    return subprocess.check_output(base_cmd, cwd=str(current_app.config['HIDDIFY_CONFIG_PATH'])).decode()

```

## Details:
**Hiddify Version**: 10.12.0
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-97-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by rezakeshavarza** [comment]
برای منم اینجوری شد چیکارش کنیم ؟

**Comment by hiddify-com** [comment]
fixed

**Comment by moli1369** [comment]
تنها راه حلش اینکه که یک ساعتی قطعی بدی و اینکه قبل از تمامی این روش حتما این کار رو انجام بده
به پشتیبان گیری برو و یه نسخه پشتیبان گیری واسه خودت بگیرد به جایی که سرور خریدی برو سرور رو ریست فکتوری کن خام شه تمامی اپدیت ها رو انجام بده مجدد پنل رو نصب کن وقتی که بالا اومد هیچکاری نکن مستقیم برو به پشتیبان گیری فایل پشتیبان رو بهش بده و ریکاوری رو بزن سرور اپدیت میشه کاریش نداشته باش تموم شد تمامی اطلاعات واست لیست میشه و مشکل اپدیت حجم برات برطرف میشه حتی آنلاین و آفلاین بودن کاربرا هم واست درست میشه کلا تمامی مشکلات حل میشه سعی کن این کار رو اخر شب انجام بدی که ترافیک سمت سرورت کمه بازم تاکید میکنم حتما پشتیبان گیری رو انجام بده.نگران حجم استفاده شده دوستان نباش بلافاصله اپدیت کنی اطلاعات پنل به روز میشه و حجم کسایی که استفاده کردن برات اپدیت میشه.
این مشکل با این کار درست میشه
