### ISSUE TITLE
update #bug and update log V 10.14.0

### ISSUE THREAD

**Issue by moli1369** [hiddify/Hiddify-Manager#3905]
####1####Hiddify Updater####Checking for update####
Checking for update...
####5####Hiddify Updater####Creating a backup####
Creating a backup ...
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/__main__.py", line 13, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/flask/cli.py", line 579, in main
    return super().main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/flask/cli.py", line 427, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/cli.py", line 42, in backup
    from hiddifypanel.panel.commercial.telegrambot import bot
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/commercial/__init__.py", line 1, in <module>
    from .ProxyDetailsAdmin import ProxyDetailsAdmin
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/commercial/ProxyDetailsAdmin.py", line 2, in <module>
    from hiddifypanel.panel.admin.adminlte import AdminLTEModelView
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/__init__.py", line 6, in <module>
    from .DomainAdmin import DomainAdmin
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/DomainAdmin.py", line 28, in <module>
    class DomainAdmin(AdminLTEModelView):
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/DomainAdmin.py", line 67, in DomainAdmin
    message=__("Should be a valid domain"))]},
  File "/usr/local/lib/python3.10/dist-packages/flask_babel/__init__.py", line 756, in gettext
    return get_domain().gettext(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/flask_babel/__init__.py", line 648, in gettext
    t = self.get_translations()
  File "/usr/local/lib/python3.10/dist-packages/flask_babel/__init__.py", line 609, in get_translations
    locale = get_locale()
  File "/usr/local/lib/python3.10/dist-packages/flask_babel/__init__.py", line 263, in get_locale
    rv = babel.locale_selector()
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/base.py", line 82, in get_locale
    if "admin" in request.base_url:
  File "/usr/local/lib/python3.10/dist-packages/werkzeug/local.py", line 278, in __get__
    obj = instance._get_current_object()
  File "/usr/local/lib/python3.10/dist-packages/werkzeug/local.py", line 407, in _get_current_object
    return self.__local()  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/flask/globals.py", line 33, in _lookup_req_object
    raise RuntimeError(_request_ctx_err_msg)
RuntimeError: Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request.  Consult the documentation on testing for
information about how to avoid this problem.
release Latest panel version: 10.14.0 Installed: 10.14.0 Lastest manager version: 10.14.0 Installed: 10.14.0
Nothing to update
---------------------Finished!------------------------

**Comment by Iam54r1n4** [comment]
Fixed.
