### ISSUE TITLE
Internal server error: Unknown

### ISSUE THREAD

**Issue by A7ireza** [hiddify/Hiddify-Manager#3928]
# Internal Error Stacktrace:
**Error Message**:   'utf-8' codec can't decode byte 0x99 in position 26: invalid start byte
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/auth.py", line 111, in decorated_view
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/Backup.py", line 46, in post
    json_data = json.load(file)

```

## Details:
**Hiddify Version**: 10.14.0
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-101-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by Iam54r1n4** [comment]
Hi, it looks like you didn't send a valid JSON file
