### ISSUE TITLE
حجم و زمان کاربرها از سی مارس آپدیت نشدن و این ارور دکمه آپدیت مصرف در صفحه کاربران هست 

### ISSUE THREAD

**Issue by amirabbbbas** [hiddify/Hiddify-Manager#3941]
حجم و زمان کاربرها از سی مارس آپدیت نشدن و این ارور دکمه آپدیت مصرف در صفحه کاربران هست 
از طرفی ربات تلگرام هم برام بک آپ ها رو نفرستاده از اون تاریخ
لطفا بررسی بشه

# Internal Error Stacktrace:
**Error Message**:   <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:10086: Failed to connect to remote host: Connection refused"
	debug_error_string = "UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:10086: Failed to connect to remote host: Connection refused {created_time:"2024-04-03T14:53:22.292039841+03:30", grpc_status:14}"
>
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/auth.py", line 111, in decorated_view
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/Actions.py", line 192, in update_usage
    out_msg=f'<pre class="ltr">{json.dumps(usage.update_local_usage(),indent=2)}</pre>',
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/usage.py", line 14, in update_local_usage
    res = user_driver.get_users_usage(reset=True)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/drivers/user_driver.py", line 21, in get_users_usage
    all_usage = driver.get_all_usage(users)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/drivers/singbox_api.py", line 51, in get_all_usage
    usages = xray_client.stats_query('user', reset=True)

```

## Details:
**Hiddify Version**: 10.14.0
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-91-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by Peyman300** [comment]
منم همین مشکل رو دارم

**Comment by litoosh13** [comment]
به آخرین نسخه آپدیت نمایید
آموزش نصب و کانفیگ صحیح پنل:
hiddify.com/manager
hiddify.com/fa/manager
