### ISSUE TITLE
Internal server error: Internal Server Error

### ISSUE THREAD

**Issue by Afx110** [hiddify/Hiddify-Manager#3951]
# Internal Error Stacktrace:
**Error Message**:   500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```
Traceback (most recent call last):
 
 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 894, in finalize_request
    response = self.process_response(response)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1274, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "/usr/local/lib/python3.10/dist-packages/flask_session/base.py", line 305, in save_session
    self._upsert_session(app.permanent_session_lifetime, session, store_id)
  File "/usr/local/lib/python3.10/dist-packages/flask_session/redis/redis.py", line 78, in _upsert_session
    serialized_session_data = self.serializer.encode(session)
  File "/usr/local/lib/python3.10/dist-packages/flask_session/base.py", line 132, in encode
    return self.encoder.encode(dict(session))
TypeError: Encoding objects of type Markup is unsupported

```

## Details:
**Hiddify Version**: 10.15.0.dev4
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-101-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by Iam54r1n4** [comment]
Fixed.
