### ISSUE TITLE
Internal server error: Unknown

### ISSUE THREAD

**Issue by idaniali** [hiddify/Hiddify-Manager#3963]
# Internal Error Stacktrace:
**Error Message**:   Expecting value: line 1 column 1 (char 0)
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/auth.py", line 111, in decorated_view
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/Backup.py", line 46, in post
    json_data = json.load(file)

```

## Details:
**Hiddify Version**: 10.14.0
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-100-generic-aarch64-with-glibc2.35
**User Agent**:      Unknown

**Comment by Iam54r1n4** [comment]
It seems your backup file is corrupted
