### ISSUE TITLE
Panel does not update usage

### ISSUE THREAD

**Issue by AR45H** [hiddify/Hiddify-Manager#3986]
# Internal Error Stacktrace:
**Error Message**:   [Errno 13] Permission denied: './hiddify_usages.json'
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/auth.py", line 114, in decorated_view
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/Actions.py", line 190, in update_usage
    out_msg=f'<pre class="ltr">{json.dumps(usage.update_local_usage(),indent=2)}</pre>',
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/usage.py", line 16, in update_local_usage
    res = user_driver.get_users_usage(reset=True)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/drivers/user_driver.py", line 21, in get_users_usage
    all_usage = driver.get_all_usage(users)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/drivers/wireguard_api.py", line 98, in get_all_usage
    all_usages = self.__sync_local_usages()
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/drivers/wireguard_api.py", line 58, in __sync_local_usages
    with open(WireguardApi.WG_LOCAL_USAGE_FILE_PATH, 'w') as f:

```

## Details:
**Hiddify Version**: 10.20.4
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-1051-oracle-aarch64-with-glibc2.35
**User Agent**:      Unknown

**Comment by ReturnFI** [comment]
Get a backup and rebuild to Ubuntu 22.04 and install latest release version
Or update to latest release version
