### ISSUE TITLE
اپدیت نشدن حجم و وضعیت کاربران و ایجاد خطای زیر

### ISSUE THREAD

**Issue by boterial** [hiddify/Hiddify-Manager#3988]
# Internal Error Stacktrace:
**Error Message**:   Expecting value: line 1 column 1 (char 0)
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/auth.py", line 114, in decorated_view
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/Actions.py", line 190, in update_usage
    out_msg=f'<pre class="ltr">{json.dumps(usage.update_local_usage(),indent=2)}</pre>',
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/usage.py", line 16, in update_local_usage
    res = user_driver.get_users_usage(reset=True)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/drivers/user_driver.py", line 21, in get_users_usage
    all_usage = driver.get_all_usage(users)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/drivers/wireguard_api.py", line 98, in get_all_usage
    all_usages = self.__sync_local_usages()
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/drivers/wireguard_api.py", line 43, in __sync_local_usages
    local_usage = self.__get_local_usage()
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/drivers/wireguard_api.py", line 39, in __get_local_usage
    data = json.load(f)

```

## Details:
**Hiddify Version**: 10.20.4
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-102-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by litoosh13** [comment]
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager
