### ISSUE TITLE
Internal server error: Unknown

### ISSUE THREAD

**Issue by mahdimirzayi120** [hiddify/Hiddify-Manager#4043]
وقتی از modified proxies یکی از کانفیک ها را به h3-quic تغییر دادم به این مشکل برخوردم

# Internal Error Stacktrace:
**Error Message**:   int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/auth.py", line 114, in decorated_view
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/user/user.py", line 48, in sub
    return self.all_configs(base64=False)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/auth.py", line 114, in decorated_view
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/user/user.py", line 233, in all_configs
    resp = hutils.proxy.xray.make_v2ray_configs(c['domains'], c['user'], c['expire_days'], c['ip_debug'])
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/hutils/proxy/xray.py", line 188, in make_v2ray_configs
    for pinfo in hutils.proxy.get_valid_proxies(domains):
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/hutils/proxy/shared.py", line 233, in get_valid_proxies
    pinfo = make_proxy(hconfigs, proxy, domain, **opt)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/hutils/proxy/shared.py", line 245, in make_proxy
    port = hutils.proxy.get_port(proxy, hconfigs, domain_db, ptls, phttp, pport)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/hutils/proxy/shared.py", line 98, in get_port
    port = int(pport)  # type: ignore

```

## Details:
**Hiddify Version**: 10.20.4
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-102-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by litoosh13** [comment]
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager
