### ISSUE TITLE
Internal server error: Unknown

### ISSUE THREAD

**Issue by rendinjast** [hiddify/Hiddify-Manager#4056]
# Internal Error Stacktrace:
**Error Message**:   [Errno 13] Permission denied: '/etc/ssh/sshd_config'
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/auth.py", line 114, in decorated_view
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/Dashboard.py", line 67, in index
    if hutils.network.is_ssh_password_authentication_enabled():
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/hutils/network/net.py", line 296, in is_ssh_password_authentication_enabled
    with open('/etc/ssh/sshd_config', 'r') as f:

```

## Details:
**Hiddify Version**: 10.20.4
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-3.10.0-1160.53.1.vz7.185.3-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by ReturnFI** [comment]
Get a backup and rebuild to Ubuntu 22.04 and install latest release version
