### ISSUE TITLE
Internal server error: Unknown

### ISSUE THREAD

**Issue by hamidrezasun** [hiddify/Hiddify-Manager#4066]
# Internal Error Stacktrace:
**Error Message**:   int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/auth.py", line 114, in decorated_view
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/Backup.py", line 67, in post
    return Actions().reinstall(complete_install=True, domain_changed=True)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/auth.py", line 114, in decorated_view
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/Actions.py", line 58, in reinstall
    return self.reinstall2(complete_install, domain_changed)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/auth.py", line 114, in decorated_view
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/Actions.py", line 62, in reinstall2
    if int(hconfig(ConfigEnum.db_version)) < 9:

```

## Details:
**Hiddify Version**: 10.20.4
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-105-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by ReturnFI** [comment]
Get a backup and rebuild to Ubuntu 22.04 and install latest release version
