### ISSUE TITLE
همه چی اوکیه، سرور دامنه آی پی. حتی کانفیگ ها هم به خوبی کار می کنن. ولی از دیروز دسترسی به پنل ندارم.آپدیت اپلای ری استارت هم کردم ولی پنل اکتیو نمیشه

### ISSUE THREAD

**Issue by sadidshop** [hiddify/Hiddify-Manager#4129]
# Internal Error Stacktrace:
**Error Message**:   [Errno 2] No such file or directory: '/proc/948/stat'
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/auth.py", line 114, in decorated_view
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/Dashboard.py", line 73, in index
    stats = {'system': hutils.system.system_stats(), 'top5': hutils.system.top_processes()}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/hutils/system.py", line 22, in top_processes
    processes = [p for p in psutil.process_iter(['name', 'memory_full_info', 'cpu_percent']) if p.info['name'] != '']
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/hutils/system.py", line 22, in <listcomp>
    processes = [p for p in psutil.process_iter(['name', 'memory_full_info', 'cpu_percent']) if p.info['name'] != '']

```

## Details:
**Hiddify Version**: 05-10T14:19
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-46-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by litoosh13** [comment]
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager
