### ISSUE TITLE
Internal server error: Unknown

### ISSUE THREAD

**Issue by MB-KING** [hiddify/Hiddify-Manager#4196]
# Internal Error Stacktrace:
**Error Message**:   Value sub_full_singbox_enable is not found in this enum type declaration
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/auth.py", line 114, in decorated_view
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/Backup.py", line 47, in post
    hiddify.set_db_from_json(json_data,
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/hiddify.py", line 230, in set_db_from_json
    bulk_register_configs(json_data["hconfigs"], commit=True, override_unique_id=override_unique_id)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/models/config.py", line 181, in bulk_register_configs
    add_or_update_config(commit=False, child_id=child_id, **conf)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/models/config.py", line 163, in add_or_update_config
    ckey = ConfigEnum(c)

```

## Details:
**Hiddify Version**: 10.20.4
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-97-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by Iam54r1n4** [comment]
You probably updated your panel to the develop version and went on release again.
Get a backup and reinstall your panel.
