### ISSUE TITLE
Internal server error: Unknown

### ISSUE THREAD

**Issue by chuyinluotian01** [hiddify/Hiddify-Manager#4314]
# Internal Error Stacktrace:
**Error Message**:   [Errno 2] No such file or directory: '/proc/754/stat'
```
Traceback (most recent call last):
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask_classful.py", line 303, in proxy
    response = view(**request.view_args)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask_classful.py", line 271, in inner
    return fn(*args, **kwargs)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/auth.py", line 130, in decorated_view
    return fn(*args, **kwargs)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/panel/admin/Dashboard.py", line 71, in index
    stats = {'system': hutils.system.system_stats(), 'top5': hutils.system.top_processes()}
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/hutils/system.py", line 22, in top_processes
    processes = [p for p in psutil.process_iter(['name', 'memory_full_info', 'cpu_percent']) if p.info['name'] != '']
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/hutils/system.py", line 22, in <listcomp>
    processes = [p for p in psutil.process_iter(['name', 'memory_full_info', 'cpu_percent']) if p.info['name'] != '']
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/psutil/__init__.py", line 1505, in process_iter
    yield add(pid)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/psutil/__init__.py", line 1484, in add
    proc = Process(pid)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/psutil/__init__.py", line 323, in __init__
    self._init(pid)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/psutil/__init__.py", line 359, in _init
    self.create_time()
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/psutil/__init__.py", line 752, in create_time
    self._create_time = self._proc.create_time()
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/psutil/_pslinux.py", line 1714, in wrapper
    return fun(self, *args, **kwargs)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/psutil/_pslinux.py", line 1945, in create_time
    ctime = float(self._parse_stat_file()['create_time'])
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/psutil/_pslinux.py", line 1714, in wrapper
    return fun(self, *args, **kwargs)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/psutil/_common.py", line 497, in wrapper
    raise raise_from(err, None)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/psutil/_pslinux.py", line 1777, in _parse_stat_file
    data = bcat("%s/%s/stat" % (self._procfs_path, self.pid))
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/psutil/_common.py", line 840, in bcat
    return cat(fname, fallback=fallback, _open=open_binary)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/psutil/_common.py", line 828, in cat
    with _open(fname) as f:
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/psutil/_common.py", line 788, in open_binary
    return open(fname, "rb", buffering=FILE_READ_BUFFER_SIZE)

```

## Details:
**Hiddify Version**: 10.50.5.dev0
**Python Version**:  3.10.12 (main, Mar 22 2024, 16:50:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-87-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by litoosh13** [comment]
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager
