### ISSUE TITLE
Internal server error: Unknown

### ISSUE THREAD

**Issue by hesanf** [hiddify/Hiddify-Manager#4315]
# Internal Error Stacktrace:
**Error Message**:   BaseModelView.delete_view() got an unexpected keyword argument 'cls'
```
Traceback (most recent call last):
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask_admin/base.py", line 369, in _run_view
    return fn(self, *args, **kwargs)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask_admin/model/base.py", line 2235, in delete_view
    if self.delete_model(model):
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask_admin/contrib/sqla/view.py", line 1216, in delete_model
    if not self.handle_view_exception(ex):
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask_admin/contrib/sqla/view.py", line 1133, in handle_view_exception
    return super(ModelView, self).handle_view_exception(exc)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask_admin/contrib/sqla/view.py", line 1211, in delete_model
    self.on_model_delete(model)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/panel/admin/DomainAdmin.py", line 288, in on_model_delete
    if not hutils.network.cf_api.delete_dns_record(model.domain):
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/hutils/network/cf_api.py", line 54, in delete_dns_record
    record = __get_dns_record(zone, domain)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/hutils/network/cf_api.py", line 72, in __get_dns_record
    dns_records = __cf.zones.dns_records(zone['id'])
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask_admin/base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask_admin/base.py", line 371, in _run_view
    return fn(cls=self, **kwargs)

```

## Details:
**Hiddify Version**: 10.50.4
**Python Version**:  3.10.14 (main, Apr 27 2024, 21:17:55) [GCC 13.2.0]
**OS**:              Linux-6.8.0-38-generic-x86_64-with-glibc2.39
**User Agent**:      Unknown

**Comment by litoosh13** [comment]
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager
