### ISSUE TITLE
Internal server error: Unknown

### ISSUE THREAD

**Issue by javadkhajavi** [hiddify/Hiddify-Manager#4345]
# Internal Error Stacktrace:
**Error Message**:   sequence item 6: expected str instance, dict found
```
Traceback (most recent call last):
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask_classful.py", line 303, in proxy
    response = view(**request.view_args)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask_classful.py", line 271, in inner
    return fn(*args, **kwargs)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/auth.py", line 130, in decorated_view
    return fn(*args, **kwargs)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/panel/user/user.py", line 42, in sub
    return self.links_imp(base64=False)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/auth.py", line 130, in decorated_view
    return fn(*args, **kwargs)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/panel/user/user.py", line 291, in links_imp
    resp = hutils.proxy.xray.make_v2ray_configs(c['domains'], c['user'], c['expire_days'], c['ip_debug'])
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/hutils/proxy/xray.py", line 197, in make_v2ray_configs
    return "\n".join(res)

```

## Details:
**Hiddify Version**: 10.70.0.dev1
**Python Version**:  3.10.12 (main, Mar 22 2024, 16:50:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-117-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by litoosh13** [comment]
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager
