### ISSUE TITLE
Internal server error: Unknown

### ISSUE THREAD

**Issue by hhaacckk333** [hiddify/Hiddify-Manager#4362]
# Internal Error Stacktrace:
**Error Message**:   'относительно'
```
Traceback (most recent call last):
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask_admin/base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask_admin/base.py", line 369, in _run_view
    return fn(self, *args, **kwargs)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask_admin/model/base.py", line 2165, in edit_view
    self.on_form_prefill(form, id)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/panel/admin/UserAdmin.py", line 238, in on_form_prefill
    form.reset_days.label.text += f" ({msg})"
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask_babel/speaklater.py", line 21, in __str__
    return str(self._func(*self._args, **self._kwargs))
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask_babel/__init__.py", line 756, in gettext
    return get_domain().gettext(*args, **kwargs)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask_babel/__init__.py", line 650, in gettext
    return s if not variables else s % variables

```

## Details:
**Hiddify Version**: 10.70.2
**Python Version**:  3.10.14 (main, Apr 27 2024, 21:17:55) [GCC 13.2.0]
**OS**:              Linux-6.8.0-36-generic-x86_64-with-glibc2.39
**User Agent**:      Unknown

        
I can't add time to an active config user (he is not online for more than 13 hours but can't add time). but I can change the config for a user who hasn't used or started his own config.

**Comment by litoosh13** [comment]
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager
