### ISSUE TITLE
Internal server error: Unknown

### ISSUE THREAD

**Issue by josephosan** [hiddify/Hiddify-Manager#4466]
# Internal Error Stacktrace:
**Error Message**:   'usage_history' is undefined
```
Traceback (most recent call last):
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask_classful.py", line 303, in proxy
    response = view(**request.view_args)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask_classful.py", line 271, in inner
    return fn(*args, **kwargs)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/auth.py", line 130, in decorated_view
    return fn(*args, **kwargs)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/panel/admin/Actions.py", line 21, in index
    return render_template('index.html')
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/panel/admin/templates/index.html", line 1, in top-level template code
    {% extends 'admin-layout.html' %}
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/templates/admin-layout.html", line 2, in top-level template code
    {% from 'macros.html' import icon,render_nav_item %}
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/templates/master.html", line 105, in top-level template code
    {% block page_body %}
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/templates/master.html", line 137, in block 'page_body'
    {% block body %}{% endblock %}
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/panel/admin/templates/index.html", line 68, in block 'body'
    {% set onlines=usage_history['m5']['online'] %}
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/jinja2/environment.py", line 468, in getitem
    return obj[argument]

```

## Details:
**Hiddify Version**: 10.70.7
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-97-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by litoosh13** [comment]
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learnings material about panel here:
hiddify.com/manager
