### ISSUE TITLE
Please fill the title properly (after recovery i can't edit the user card in the panel)

### ISSUE THREAD

**Issue by glory7sa** [hiddify/Hiddify-Manager#4520]
![Screenshot_20241014_091302_Chrome](https://github.com/user-attachments/assets/45fbfa95-8c18-4a0a-9349-86e38a33b743)
![Screenshot_20241014_091313_Chrome](https://github.com/user-attachments/assets/d0fb64d4-5374-423a-8dc8-4228b02b017b)
# Bug/Feature:
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 10.70.7
**Python Version**:  3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
**OS**:              Linux-5.15.0-113-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by glory7sa** [comment]
hiddify_panel.err.log


Usage:
 kill [options] <pid> [...]

Options:
 <pid> [...]            send signal to every <pid> listed
 -<signal>, -s, --signal <signal>
                        specify the <signal> to be sent
 -q, --queue <value>    integer value to be sent with the signal
 -l, --list=[<signal>]  list all signal names, or convert one to a name
 -L, --table            list all signal names in a nice table

 -h, --help     display this help and exit
 -V, --version  output version information and exit

For more details see kill(1).
3.10/site-packages/redis_cache/__init__.py", line 221, in inner
    parsed_result = fn(*args, **kwargs)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/panel/commercial/restapi/v1/tgbot.py", line 23, in register_bot_cached
    return register_bot(set_hook, remove_hook)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/panel/commercial/restapi/v1/tgbot.py", line 50, in register_bot
    traceback.print_stack()
in server_run
    _bjoern.server_run(*args)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/werkzeug/middleware/proxy_fix.py", line 182, in __call__
    return self.app(environ, start_response)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask_classful.py", line 303, in proxy
    response = view(**request.view_args)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask_classful.py", line 271, in inner
    return fn(*args, **kwargs)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/auth.py", line 130, in decorated_view
    return fn(*args, **kwargs)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/panel/admin/SettingAdmin.py", line 118, in post
    register_bot(set_hook=True)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/panel/commercial/restapi/v1/tgbot.py", line 50, in register_bot
    traceback.print_stack()
, '/opt/hiddify-manager/common/commander.py', 'update-wg-usage']' returned non-zero exit status 1.
ERROR! XrayApi has error in get_enabled users <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:10085: Failed to connect to remote host: connect: Connection refused (111)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-10-13T08:08:02.101918777+03:30", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:10085: Failed to connect to remote host: connect: Connection refused (111)"}"
>
Unable to access interface: No such device
Traceback (most recent call last):
  File "/opt/hiddify-manager/common/commander.py", line 165, in <module>
    cli()
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/click/core.py", line 1719, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/hiddify-manager/common/commander.py", line 160, in update_wg_usage
    wg_raw_output = subprocess.check_output(['wg', 'show', 'hiddifywg', 'transfer'])
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['wg', 'show', 'hiddifywg', 'transfer']' returned non-zero exit status 1.
ERROR! WireguardApi has error in get_enabled users Command '['sudo', '/opt/hiddify-manager/common/commander.py', 'update-wg-usage']' returned non-zero exit status 1.

**Comment by glory7sa** [comment]
Advise settings for Russia

**Comment by glory7sa** [comment]
+ the banner doesn't appear. At the end of an action, sometimes it appears, sometimes it does not. 
![Screenshot_20241014_100238_Chrome](https://github.com/user-attachments/assets/d445b801-5c37-41ad-b044-139cbfa6d54e)

**Comment by litoosh13** [comment]
hi this is a known bug in Russia version of the panel
please while we are trying to fix the problem use English version
