### ISSUE TITLE
Error when restore the backup file from v10.80.0.dev13 on Hiddify Manager v10.70.9

### ISSUE THREAD

**Issue by lloydeastin** [hiddify/Hiddify-Manager#4599]
Error shows as below. When I used the backup file from v10.70.7, it works well.

# Internal Error Stacktrace:
**Error Message**:   Value ssh_host_rsa_pk is not found in this enum type declaration
```
Traceback (most recent call last):
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask_classful.py", line 303, in proxy
    response = view(**request.view_args)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/auth.py", line 130, in decorated_view
    return fn(*args, **kwargs)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask_classful.py", line 271, in inner
    return fn(*args, **kwargs)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/panel/admin/Backup.py", line 44, in post
    hiddify.set_db_from_json(json_data,
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/panel/hiddify.py", line 235, in set_db_from_json
    bulk_register_configs(json_data["hconfigs"], commit=True, override_unique_id=override_unique_id)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/models/config.py", line 172, in bulk_register_configs
    add_or_update_config(commit=False, child_id=child_id, **conf)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/models/config.py", line 156, in add_or_update_config
    ckey = ConfigEnum(c)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/fast_enum/fastenum.py", line 158, in get
    raise ValueError(f'Value {val} is not found in this enum type declaration')

```

## Details:
**Hiddify Version**: 10.70.9
**Python Version**:  3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
**OS**:              Linux-5.15.0-124-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by naymintun800** [comment]
have you found a way to solve this yet? I'm having same issue.

**Comment by litoosh13** [comment]
we aware of the problem
here is the solution:
https://t.me/hiddify_board/482495/518026

**Comment by naymintun800** [comment]
![Uploading Screenshot from 2024-11-19 16-38-28.png…]()

After running "bash /opt/hiddify-manager/update.sh release --no-gui" I can't open the hiddify manager panel anymore. help

**Comment by litoosh13** [comment]
backup then rebuild and install again 
then use your backup

**Comment by naymintun800** [comment]
I'm at "v10.70.9" and I can't restore backup file from  "v10.80.0.dev14" so I'm guessing that I need to upgrade to "v10.80.0.dev14" again and then run the command "bash /opt/hiddify-manager/update.sh release --no-gui" ?
