### ISSUE TITLE
Internal server error: Unknown

### ISSUE THREAD

**Issue by vgfchen** [hiddify/Hiddify-Manager#4607]
# Internal Error Stacktrace:
**Error Message**:   list index out of range
```
Traceback (most recent call last):
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask_classful.py", line 303, in proxy
    response = view(**request.view_args)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask_classful.py", line 271, in inner
    return fn(*args, **kwargs)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/auth.py", line 130, in decorated_view
    return fn(*args, **kwargs)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/panel/user/user.py", line 59, in xray
    configs = hutils.proxy.xrayjson.configs_as_json(c['domains'], c['user'], c['expire_days'], c['profile_title'])
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/hutils/proxy/xrayjson.py", line 81, in configs_as_json
    base_config['outbounds'].insert(0, outbounds[0])

```

## Details:
**Hiddify Version**: 10.70.9
**Python Version**:  3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
**OS**:              Linux-5.15.0-124-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by z2ray** [comment]
این خطا به دلیل عدم یکسان بودن نسخه Backup و نسخه نصب شده ایجاد شده
اگه از backup نسخه بتا استفاده میکنید بهتره فقط کاربران را بازیابی کنید و بخش تنظیمات و دامنه های رو دستی وارد کنید یا backup نسخه هماهنگ با stable را بازیابی کنید
