### ISSUE TITLE
Internal server error: Unknown

### ISSUE THREAD

**Issue by MasterHide** [hiddify/Hiddify-Manager#4613]
# Internal Error Stacktrace:
**Error Message**:   Value xhttp_enable is not found in this enum type declaration
```
Traceback (most recent call last):
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask_classful.py", line 303, in proxy
    response = view(**request.view_args)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/auth.py", line 130, in decorated_view
    return fn(*args, **kwargs)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask_classful.py", line 271, in inner
    return fn(*args, **kwargs)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/panel/admin/Backup.py", line 44, in post
    hiddify.set_db_from_json(json_data,
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/panel/hiddify.py", line 235, in set_db_from_json
    bulk_register_configs(json_data["hconfigs"], commit=True, override_unique_id=override_unique_id)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/models/config.py", line 172, in bulk_register_configs
    add_or_update_config(commit=False, child_id=child_id, **conf)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/models/config.py", line 156, in add_or_update_config
    ckey = ConfigEnum(c)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/fast_enum/fastenum.py", line 158, in get
    raise ValueError(f'Value {val} is not found in this enum type declaration')

```

## Details:
**Hiddify Version**: 10.70.9
**Python Version**:  3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]
**OS**:              Linux-6.8.0-1016-oracle-aarch64-with-glibc2.35
**User Agent**:      Unknown

**Comment by MasterHide** [comment]
i cant upload my backup

**Comment by litoosh13** [comment]
what is the problem ?

**Comment by litoosh13** [comment]
will be closed soon !!!
