### ISSUE TITLE
خطا هنگام اضافه کردن سایت PHP

### ISSUE THREAD

**Issue by pourmirzai** [hiddify/Hiddify-Manager#4621]
سلام من طبق آموزش پیش رفتم و پنل ادمین با دامنه PHP باز میشه. اما وقتی اشتراک میسازم و می‌خوام بازش کنم این خطا رو دریافت کردم.
# Internal Error Stacktrace:
**Error Message**:   '194.59.249.204194.59.249.204' does not appear to be an IPv4 or IPv6 address.
```
Traceback (most recent call last):
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask_classful.py", line 303, in proxy
    response = view(**request.view_args)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask_classful.py", line 271, in inner
    return fn(*args, **kwargs)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/panel/user/user.py", line 22, in index
    return self.auto_sub()
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/panel/user/user.py", line 26, in auto_sub
    return self.new()
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/auth.py", line 130, in decorated_view
    return fn(*args, **kwargs)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/panel/user/user.py", line 137, in new
    c = get_common_data(g.account.uuid, mode="new")
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/panel/user/user.py", line 415, in get_common_data
    "ip_debug": hutils.network.auto_ip_selector.get_real_user_ip_debug(user_ip),
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/hutils/network/auto_ip_selector.py", line 114, in get_real_user_ip_debug
    return __get_real_user_ip_debug_imp(user_ip or get_real_user_ip())
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/redis_cache/__init__.py", line 221, in inner
    parsed_result = fn(*args, **kwargs)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/hutils/network/auto_ip_selector.py", line 121, in __get_real_user_ip_debug_imp
    asnres = IPASN.get(user_ip) or {}

```

## Details:
**Hiddify Version**: 10.70.9
**Python Version**:  3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]
**OS**:              Linux-5.15.0-126-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by litoosh13** [comment]
سلام مشکل از هاست هست بعضی هاست ها ساپورت نمیکنن این مورد رو با هاست خارجی یکبار چک کنید

**Comment by litoosh13** [comment]
بزودی بسته می شود
