### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by alexlii1971** [hiddify/Hiddify-Manager#4718]
500

Oops! something went wrong. Hiddify Panel 10.80.11

Please create an issue on Github

 
        
405 Method Not Allowed: The method is not allowed for the requested URL.
Traceback (most recent call last):
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask/app.py", line 854, in dispatch_request
    self.raise_routing_exception(req)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask/app.py", line 463, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/werkzeug/routing/map.py", line 624, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.

**Comment by alexlii1971** [comment]
Really confused, same sever configuration:

1 CPU Core
25 GB Storage
1 GB RAM

 Linode works, but Digitalocean failed.
 
 Also, there is almost no free memory on Digitalocean, but there are lots of memory left:
 
 MiB Mem :    957.4 total,    224.9 free,    533.8 used,    198.8 buff/cache
MiB Swap:    512.0 total,    330.0 free,    182.0 used.    287.3 avail Mem

**Comment by litoosh13** [comment]
try our new docker release if you face error with docker
